# N8N Deployment Project Configuration
# ====================================

# Project Information
project:
  name: "n8n-deployment"
  version: "1.0.0"
  description: "Automated N8N deployment project"
  author: "N8N Deployment Team"
  license: "MIT"

# Git Configuration
git:
  # User information for commits
  user:
    name: "N8N Deployer"
    email: "deployer@n8n-project.local"
  
  # Commit settings
  auto_commit: true
  commit_message_template: "🚀 Auto-deploy: {timestamp}"
  branch: "main"
  
  # Remote repository settings
  remote:
    name: "origin"
    url: ""  # Set this to your Git repository URL
  
  # Files to ignore in commits
  ignore_patterns:
    - "*.log"
    - "*.tmp"
    - ".env"
    - "secrets/"
    - "backups/"

# N8N Configuration
n8n:
  # Basic settings
  port: 5678
  host: "0.0.0.0"
  protocol: "http"
  webhook_url: "http://localhost:5678"
  timezone: "UTC"
  secure_cookie: false
  
  # Database configuration
  database_type: "sqlite"  # Options: sqlite, postgres, mysql
  
  # PostgreSQL settings (if database_type is postgres)
  postgres:
    host: "postgres"
    port: 5432
    database: "n8n"
    user: "n8n"
    password: "n8n_password"
  
  # MySQL settings (if database_type is mysql)
  mysql:
    host: "mysql"
    port: 3306
    database: "n8n"
    user: "n8n"
    password: "n8n_password"
    root_password: "root_password"
  
  # SSL/TLS configuration
  ssl_enabled: false
  ssl:
    key_path: "/certs/key.pem"
    cert_path: "/certs/cert.pem"
    generate_self_signed: true
  
  # Performance settings
  performance:
    max_execution_timeout: 3600
    max_execution_data_size: "50MB"
    executions_process: "main"
    executions_mode: "regular"
  
  # Security settings
  security:
    jwt_secret: ""  # Will be auto-generated if empty
    encryption_key: ""  # Will be auto-generated if empty
    basic_auth:
      enabled: false
      user: "admin"
      password: "admin"

# Docker Configuration
docker:
  # Docker Compose settings
  compose_version: "3.8"
  restart_policy: "unless-stopped"
  
  # Container settings
  container_name: "n8n"
  image: "docker.n8n.io/n8nio/n8n"
  
  # Volume settings
  volumes:
    data_volume: "n8n_data"
    files_directory: "./local-files"
    logs_directory: "./logs"
  
  # Network settings
  network:
    name: "n8n_network"
    driver: "bridge"

# Logging Configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/deployment.log"
  max_size: "10MB"
  backup_count: 5
  
  # Log format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  
  # Console logging
  console:
    enabled: true
    level: "INFO"
    colored: true

# Backup Configuration
backup:
  # Automatic backup settings
  enabled: true
  schedule: "daily"  # Options: hourly, daily, weekly
  retention_days: 30
  
  # Backup location
  directory: "./backups"
  filename_template: "n8n-backup-{timestamp}.tar.gz"
  
  # Compression settings
  compression: "gzip"
  compression_level: 6

# Monitoring Configuration
monitoring:
  # Health checks
  health_check:
    enabled: true
    interval: 30  # seconds
    timeout: 10   # seconds
    retries: 3
  
  # Metrics collection
  metrics:
    enabled: false
    port: 9090
    endpoint: "/metrics"
  
  # Alerting
  alerts:
    enabled: false
    webhook_url: ""
    email:
      enabled: false
      smtp_host: ""
      smtp_port: 587
      username: ""
      password: ""
      from_address: ""
      to_addresses: []

# Development Configuration
development:
  # Debug settings
  debug: false
  verbose: false
  
  # Development tools
  hot_reload: false
  auto_restart: true
  
  # Testing
  test_mode: false
  mock_external_apis: false

# Production Configuration
production:
  # Performance optimizations
  optimize_for_production: true
  enable_caching: true
  
  # Security hardening
  security_headers: true
  rate_limiting: true
  
  # Scaling
  cluster_mode: false
  worker_processes: 1

# Deployment Configuration
deployment:
  # Environment
  environment: "development"  # Options: development, staging, production
  
  # Pre-deployment checks
  checks:
    docker_available: true
    disk_space_gb: 5
    memory_mb: 1024
    network_connectivity: true
  
  # Post-deployment actions
  post_deploy:
    run_health_check: true
    send_notification: false
    create_backup: true
  
  # Rollback settings
  rollback:
    enabled: true
    keep_previous_versions: 3
    auto_rollback_on_failure: false

# Integration Configuration
integrations:
  # External services
  external_services:
    enabled: false
    services: []
  
  # Webhooks
  webhooks:
    enabled: true
    base_url: "http://localhost:5678/webhook"
  
  # API settings
  api:
    enabled: true
    rate_limit: 100  # requests per minute
    authentication: "none"  # Options: none, basic, jwt

# Notification Configuration
notifications:
  # Deployment notifications
  deployment:
    enabled: false
    channels: []  # Options: email, slack, discord, webhook
  
  # Error notifications
  errors:
    enabled: false
    channels: []
  
  # Slack integration
  slack:
    webhook_url: ""
    channel: "#deployments"
    username: "N8N Deployer"
  
  # Email integration
  email:
    smtp_host: ""
    smtp_port: 587
    username: ""
    password: ""
    from_address: ""
    to_addresses: []

# Custom Configuration
custom:
  # Add your custom configuration here
  # This section is for user-specific settings
  # that don't fit into the standard categories
  
  # Example:
  # my_custom_setting: "value"
  # my_custom_list:
  #   - "item1"
  #   - "item2"