name: Deploy N8N Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint Python code
      run: |
        pip install flake8
        flake8 scripts/ --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Test configuration validation
      run: |
        python -c "import yaml; yaml.safe_load(open('config/config.yaml'))"
        python -c "import yaml; yaml.safe_load(open('config/git_config.yaml'))"
    
    - name: Test script imports
      run: |
        cd scripts
        python -c "import script, file_reader, git_deployer, setup_n8n"
    
    - name: Validate Docker Compose
      run: |
        docker-compose -f templates/docker-compose.yml config

  deploy-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test deployment (dry run)
      run: |
        chmod +x deploy.sh
        ./deploy.sh --dry-run --verbose
    
    - name: Test N8N setup (dry run)
      run: |
        ./deploy.sh --setup-n8n --dry-run --verbose